# 단일회사 전체 재무제표 목록

class FsMapper:
    def map(self, string):
        # Maps Korean
        financial_statments_list = {
            '유동자산': 'CurrAssets',
            '현금및현금성자산': 'CashAndCashEquivalents',
            '주식선택권': 'stockOption',
            '재고자산': 'Inventories',
            '매각예정분류자산': 'NoncurrAssetsDispGrpHFSLHFDistOwn',
            '비유동자산': 'NoncurrAssets',
            '종속기업, 관계기업 및 공동기업 투자': 'InvstmtsInSubsAndAssoc',
            '유형자산': 'PropertyPlantAndEquipment',
            '이연법인세자산': 'DeferredTaxAssets',
            '자산총계': 'Assets',
            '유동부채': 'CurrLiabilities',
            '단기차입금': 'ShortTermBorrowings',
            '미지급법인세': 'PaymentsOfIncomeTaxesPayable',
            '유동성장기부채': 'CurrPortionLTBorrowings',
            '충당부채': 'CurrProvisions',
            '매각예정분류부채': 'LiabInDispGrpHFSL',
            '비유동부채': 'NoncurrLiabilities',
            '이연법인세부채': 'DeferredTaxLiabilities',
            '장기충당부채': 'NoncurrProvisions',
            '부채총계': 'Liabilities',
            '이익잉여금(결손금)': 'RetainedEarnings',
            '기타자본항목': 'ElementsOSE',
            '기말자본': 'Equity',
            '자본과부채총계': 'EquityAndLiabilities',
            '수익(매출액)': 'Revenue',
            '매출원가': 'CostOfSales',
            '매출총이익': 'GrossProfit',
            '판매비와관리비': 'TotalSellingGenAdminExp',
            '영업이익(손실)': 'OperatingIncomeLoss',
            '기타수익': 'OtherGains',
            '기타비용': 'OtherLosses',
            '금융수익': 'FinanceIncome',
            '금융비용': 'FinanceCosts',
            '법인세비용차감전순이익(손실)': 'ProfitLossBeforeTax',
            '법인세비용': 'IncomeTaxExpContinuingOps',
            '계속영업이익(손실)': 'ProfitLossContOp',
            '당기순이익(손실)': 'ProfitLoss',
            '기본주당이익(손실) (단위:원)': 'BasicEPS',
            '희석주당이익(손실) (단위:원)': 'DilutedEPS',
            '기타포괄손익': 'OCI',
            '후속적으로 당기손익으로 재분류되지 않는 포괄손익': 'OCIWillNotReclassProfitLossNetTax',
            '순확정급여자산 재측정요소': 'OCINetTaxGainsLossesDBRemeas',
            '후속적으로 당기손익으로 재분류되는 포괄손익': 'OCIWillReclassProfitLossNetTax',
            '매도가능금융자산평가손익': 'OCINetTaxAFSFA',
            '총포괄손익': 'ComprehensiveIncome',
            '영업활동 현금흐름': 'CFFOA',
            '이자의 수취': 'IntReceivedOpAct',
            '이자의 지급': 'IntPaidOpAct',
            '배당금 수입': 'DivReceivedOpAct',
            '법인세 납부액': 'TaxPaidRefOpAct',
            '투자활동 현금흐름': 'CFFIA',
            '단기매도가능금융자산의 처분': 'ProceedsAFSFA',
            '단기매도가능금융자산의 취득': 'PurchaseAFSFA',
            '장기금융상품의 처분': 'ProceedsLTFI',
            '장기금융상품의 취득': 'PurchaseLTFI',
            '장기매도가능금융자산의 처분': 'ProceedsNCAFSFA',
            '장기매도가능금융자산의 취득': 'PurchaseNCAFSFA',
            '유형자산의 처분': 'ProceedsPPEInvAct',
            '유형자산의 취득': 'PurchasePPEInvAct',
            '무형자산의 처분': 'ProceedsIntgInvAct',
            '무형자산의 취득': 'PurchaseIntgInvAct',
            '재무활동 현금흐름': 'CFFFA',
            '자기주식의 취득': 'AcqTreasuryShares',
            '자기주식의 처분': 'IncDecTreasurySharesTrans',
            '사채 및 장기차입금의 상환': 'RepayLTBorrowings',
            '배당금 지급': 'DivPaidFinAct',
            '외화환산으로 인한 현금의 변동': 'EffectExchangeRateCash',
            '현금 및 현금성자산의 순증가(감소)': 'IncDecCashEquiv',
            '기초 현금 및 현금성자산': 'BegCashEquivCF',
            '기말 현금 및 현금성자산': 'EndCashEquivCF',
            '기초자본': 'BegEquity',
            '매도가능금융자산평가': 'GainValAFSFA',
            '배당': 'IncDecOtherDistOwners'
        }
